# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 765)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.widget_7 = QtGui.QWidget(self.widget)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_7)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widget_2 = QtGui.QWidget(self.widget_7)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(379, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.title_label = QtGui.QLabel(self.widget_2)
        self.title_label.setObjectName(_fromUtf8("title_label"))
        self.horizontalLayout.addWidget(self.title_label)
        spacerItem1 = QtGui.QSpacerItem(379, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_6 = QtGui.QWidget(self.widget_7)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.widget_3 = QtGui.QWidget(self.widget_6)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget_4 = QtGui.QWidget(self.widget_3)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(158, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.member_label = QtGui.QLabel(self.widget_4)
        self.member_label.setObjectName(_fromUtf8("member_label"))
        self.horizontalLayout_2.addWidget(self.member_label)
        spacerItem3 = QtGui.QSpacerItem(157, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.widget_4)
        self.line_2 = QtGui.QFrame(self.widget_3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.member_list_view = QtGui.QListView(self.widget_3)
        self.member_list_view.setObjectName(_fromUtf8("member_list_view"))
        self.verticalLayout.addWidget(self.member_list_view)
        self.view_member_btn = QtGui.QPushButton(self.widget_3)
        self.view_member_btn.setObjectName(_fromUtf8("view_member_btn"))
        self.verticalLayout.addWidget(self.view_member_btn)
        self.add_member_btn = QtGui.QPushButton(self.widget_3)
        self.add_member_btn.setObjectName(_fromUtf8("add_member_btn"))
        self.verticalLayout.addWidget(self.add_member_btn)
        self.horizontalLayout_4.addWidget(self.widget_3)
        self.line = QtGui.QFrame(self.widget_6)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_4.addWidget(self.line)
        self.widget_5 = QtGui.QWidget(self.widget_6)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget_8 = QtGui.QWidget(self.widget_5)
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_8)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem4 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.event_label = QtGui.QLabel(self.widget_8)
        self.event_label.setObjectName(_fromUtf8("event_label"))
        self.horizontalLayout_3.addWidget(self.event_label)
        spacerItem5 = QtGui.QSpacerItem(79, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_2.addWidget(self.widget_8)
        self.line_3 = QtGui.QFrame(self.widget_5)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_2.addWidget(self.line_3)
        self.event_list_view = QtGui.QListView(self.widget_5)
        self.event_list_view.setObjectName(_fromUtf8("event_list_view"))
        self.verticalLayout_2.addWidget(self.event_list_view)
        self.view_event_btn = QtGui.QPushButton(self.widget_5)
        self.view_event_btn.setObjectName(_fromUtf8("view_event_btn"))
        self.verticalLayout_2.addWidget(self.view_event_btn)
        self.add_event_btn = QtGui.QPushButton(self.widget_5)
        self.add_event_btn.setObjectName(_fromUtf8("add_event_btn"))
        self.verticalLayout_2.addWidget(self.add_event_btn)
        self.horizontalLayout_4.addWidget(self.widget_5)
        self.verticalLayout_3.addWidget(self.widget_6)
        self.gridLayout_2.addWidget(self.widget_7, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.title_label.setText(_translate("MainWindow", "Club Management", None))
        self.member_label.setText(_translate("MainWindow", "Members", None))
        self.view_member_btn.setText(_translate("MainWindow", "View Selected Member", None))
        self.add_member_btn.setText(_translate("MainWindow", "Add Member", None))
        self.event_label.setText(_translate("MainWindow", "Events", None))
        self.view_event_btn.setText(_translate("MainWindow", "View Selected Event", None))
        self.add_event_btn.setText(_translate("MainWindow", "Add Event", None))

